export BUN_INSTALL=$HOME/.bun
export CARGO_TARGET_DIR=$HOME/.cargo/target
export CPPFLAGS='-I/opt/homebrew/opt/llvm/include'
export DISPLAY=localhost:0
export DO_NOT_TRACK=1
export EDITOR='code --wait'
export FONTAWESOME_NPM_AUTH_TOKEN={{FONTAWESOME_NPM_AUTH_TOKEN}}
export GPG_TTY=$(tty)
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs/home"
export LDFLAGS='-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++'
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib:/opt/homebrew/lib
export PATH=$ICLOUD/coding/bin:$HOME/.cargo/bin:$BUN_INSTALL/bin:/opt/homebrew/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/llvm/bin:$PATH
export RAILS_UID=$UID
export TZ=UTC
